### PR TITLE
Rewrap statute histories while move them back to top

### PR DESCRIPTION
**Pull request by rschiang**
@shouko 
It is a common practice to put all histories on top, as all legal code does. Additional formatting strings should be introduced if we were putting them to the bottom. (Date formatting is inconsistent also, should we normalize it?)

### CODE REVIEW

**Comment by shouko** [comment]
Umm, this document was reproduced from that provided by school authorities without modifications.
Not sure what we should do with it wwww

**Comment by rschiang** [comment]
If we were putting earlier histories at the end of this document, they should probably be correctly formatted (as the printed version did not contain them); or should we remove them altogether?

**Comment by shouko** [comment]
@artistic709 
What do you think?

**Comment by rschiang** [comment]
哇哦哦是來回 merge! （不知道該怎麼取名XD）

謝謝翔子(・∀・)

**Pull request merged**
